reporting.enabled=true
reporting.server.hostname=https://vspitsyn.zebrunner.dev
reporting.server.access-token=
reporting.run.display-name=Incognito Download Test
reporting.tcm.zebrunner.push-results=true